---
sudo: required

language: python

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
  - sudo service docker restart
  - echo $TRAVIS_DOCKER_PASSWORD | docker login --username="$TRAVIS_DOCKER_USERNAME" --password-stdin
  - docker info

env:
  global:
    - REPOSITORY=osism/cobbler
  matrix:
    - VERSION=2.8
      BRANCH=release28

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
